use_frameworks!

platform :ios, '9.0'

target 'extension-recipes_Example' do
  pod 'extension-recipes', :path => '../'

  target 'extension-recipes_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
